CXX = g++  # Comando de compilación de C++
CXXFLAGS = -std=c++14 -Wall  # Las opciones del compilador de C++

all:
	$(CXX) $(CXXFLAGS) -o  search-a *.cc
	$(CXX) $(CXXFLAGS) -c  search-a *.cc

clean :
	rm -f *.o
	rm search-a