CXX = g++  # Comando de compilación de C++
CXXFLAGS = -std=c++14 -Wall  # Las opciones del compilador de C++

all:
	$(CXX) $(CXXFLAGS) -o  three-words *.cc
 $(CXX) $(CXXFLAGS) -c  three-words *.cc

clean :
	rm -f *.o
	rm three-words