CXX = g++  # Comando de compilación de C++
CXXFLAGS = -std=c++14 -Wall  # Las opciones del compilador de C++

all:
	$(CXX) $(CXXFLAGS) -o  divisors *.cc
	$(CXX) $(CXXFLAGS) -c  divisors *.cc

clean :
	rm -f *.o
	rm divisors